### ISSUE TITLE
运行项目报错了，缺少了config.js文件

### ISSUE THREAD

**Issue by kirbystudy** [MagmaBlock/LavaAnimeLibServerV2#2]

**Comment by MagmaBlock** [comment]
本项目目前还没有实现自行部署使用，仅是将源码公开出来。
config.json 有模板可以仿造一个创建，但仅配置好 config，数据库表的生成语句我目前也没写进去... 番剧入库管理、自动下载等等一系列的功能也都没有解耦合或者没有实现，没法用
